### PR TITLE
WIP: Dain/integrate next js for example app

### PR DESCRIPTION
**Pull request by dblodorn**
## Test NextJs App:

This is for developing against when creating standalone react packages.
Web3 dependencies are included in the test app ie. walletconnect, ethers, wagmi.

Thinking of including zoralabs deps too along with configuration.
- zdk
- nft-hooks
- nft-components

Also included MDX to enable markdown rendering:
[https://mdxjs.com/](https://mdxjs.com/)

- [ ] show readme rendering example
- [ ] integrate zdk / datafetching / utils in example app
- [ ] Improve documentation.

Dependencies included:
```
"dependencies": {
    "@fontsource/ia-writer-mono": "^4.5.3",
    "@fontsource/inter": "^4.5.12",
    "@rainbow-me/rainbowkit": "^0.5.3",
    "ethers": "^5.7.1",
    "lodash": "^4.17.21",
    "next": "12.3.0",
    "nextjs-progressbar": "^0.0.14",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "swr": "^1.3.0",
    "wagmi": "^0.6.6"
  },
  "devDependencies": {
    "@mdx-js/loader": "^2.1.3",
    "@types/lodash": "^4.14.185",
    "@types/node": "18.7.18",
    "@types/react": "18.0.20",
    "autoprefixer": "^10.4.11",
    "eslint": "8.23.1",
    "eslint-config-next": "12.3.0",
    "postcss": "^8.4.16",
    "tailwindcss": "^3.1.8",
    "typescript": "4.8.3"
  }
```

Screen Shot 2022-09-14 at 5 10 45 PM

### CODE REVIEW

**Comment by dblodorn** [comment]
Will include video walkthrough when work is ready to be merged to main @Valcoholics @0xTranqui

**Review by Javier-Szyfer — APPROVED** [review]
LGTM!

**Review by salieflewis — COMMENTED** [review]
So inside of the npm-package-boilerplate, there is a testing environment for interacting with in-progress components correct? This PR is essentially configuring that testing environment to depend on our little web3 stack? (rainbow, wagmi, ethers...)

Just trying to think out loud and understand fully. Also is there a reason we are opinionated on the data fetcher? Why SWR vs URQL or Apollo or Graph Client?

**Comment by dblodorn** [comment]
@salieflewis
Correct - this could also be used as an example directory to illustrate how package can slot into an app... could have a vanilla react example as well.

SWR is used to keep our data up to date... and can just use regular fetch api.
[https://swr.vercel.app/](https://swr.vercel.app/)

I haven't really explored the other data fetcher libraries tbh.

SWR seems to be especially well suited for next apps. But totally down to check out additional techniques if needed.

**Review by 0xTranqui — APPROVED** [review]
looks good to me @dblodorn. I would also be down to include a decent amount of the ZORA stack in this as well, the ones you mentioned + maybe the drop contracts/v3 ??

**Comment by 0xTranqui** [comment]
> @salieflewis Correct - this could also be used as an example directory to illustrate how package can slot into an app... could have a vanilla react example as well.
> 
> SWR is used to keep our data up to date... and can just use regular fetch api. https://swr.vercel.app/
> 
> I haven't really explored the other data fetcher libraries tbh.
> 
> SWR seems to be especially well suited for next apps. But totally down to check out additional techniques if needed.

@dblodorn using URQL or Apollo could be interesting as we explore the idea of moving away from Next + Vercel, but I think thats a convo for another day

**Comment by dblodorn** [comment]
Merging to show @Javier-Szyfer how to use.

**Pull request merged**
